language: node_js

node_js:
  - 6.1

sudo: required # Until Yarn repo is added to apt-source-whitelist

addons:
  apt:
    packages:
      - git

cache:
  directories:
  - node_modules
  - $HOME/.yarn-cache

before_install:
  - ./scripts/bootstrap-env-ubuntu.sh

install:
  - yarn install

before_script:
  - yarn test

script:
  - yarn run dev

os:
  - linux